openapi: "3.0.0"

info:
  title: LexImpact
  version: 1.1.0

paths:
  /:
    get:
      summary: Renvoie un message de bienvenue
      operationId: server.handlers.Welcome.home
      responses:
          '200':
            description: Un petit bonjour
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Greetings'
  /calculate/revenus:
    post:
      summary: Calcule l'impact par cas types
      operationId: server.handlers.CasTypes.revenus
      responses:
          '201':
            description: Renvoie les revenus des cas types. Utilisé seulement par l'API Dash
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/revenus'
  /metadata/description_cas_types:
    post:
      summary: Decrit les cas types
      operationId: server.handlers.CasTypes.description_cas_types
      responses:
        '201':
          description: Renvoie la description des cas types par défaut
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/description_cas_types'
  /calculate/compare:
    post:
      summary: Calcule l'impact d'une loi
      operationId: server.handlers.SimulationRunner.simulereforme
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/compareoldnew'
      responses:
          '201':
            description: Qu'est ce que c'est description
  /calculate/simpop:
    post:
      summary: Calcule l'impact d'une loi sur la population (nécessite des données)
      operationId: server.handlers.SimulationRunner.simuledeciles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/compareoldnew'
      responses:
          '201':
            description: Impact de la loi sur les recettes de l'Etat et les déciles.
  /auth/login:
    post:
      summary: Authentifie l'usager
      operationId: server.handlers.auth.login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
      responses:
          '201':
            description: L'usager a pu étre authentifié·e
          '401':
            description: L'usager n'est pas dans la liste validée par l'INSEE
  /dotations:
    post:
      summary: Demande le calcul de l'impact des articles de loi sur les dotations aux collectivités.
      operationId: server.handlers.Dotations.simule_dotations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dotations'
      responses:
          '201':
            description: Résultat de la simulation des dotations aux collectivités.
components:
  schemas:
    Greetings:
      type: object
      properties:
        hello:
          type: string
    revenus:
      type: object
    compareoldnew:
      type: object
      properties:
        token:
          type: string
        deciles:
          type: boolean
        timestamp:
          type: string
        reforme:
          type: object
          properties:
            impot_revenu:
              type: object
              properties:
                bareme:
                  type: object
                  properties:
                    seuils:
                      type: array
                      items:
                        type: integer
                    taux:
                      type: array
                      items:
                        type: number
                decote:
                  type: object
                  properties:
                    seuil_celib:
                      type: integer
                    seuil_couple:
                      type: integer
                    taux:
                      type: number
                plafond_qf:
                  type: object
                  properties:
                    maries_ou_pacses:
                      type: integer
                    celib_enf:
                      type: integer
                    celib:
                      type: integer
                    reduc_postplafond:
                      type: integer
                    reduc_postplafond_veuf:
                      type: integer
                    abat_dom:
                      type: object
                      properties:
                        taux_GuadMarReu:
                          type: number
                        plaf_GuadMarReu:
                          type: integer
                        taux_GuyMay:
                          type: number
                        plaf_GuyMay:
                          type: integer
                    reduction_ss_condition_revenus:
                      type: object
                      properties:
                        seuil_maj_enf:
                          type: integer
                        seuil1:
                          type: integer
                        seuil2:
                          type: integer
                        taux:
                          type: number
                abattements_rni:
                  type: object
                  properties:
                    personne_agee_ou_invalide:
                      type: object
                      properties:
                        montant_1:
                          type: integer
                        montant_2:
                          type: integer
                        plafond_1:
                          type: integer
                        plafond_2:
                          type: integer
                calculNombreParts:
                  type: object
                  properties:
                    partsSelonNombrePAC:
                      type: array
                      items:
                        type: object
                        properties:
                          veuf:
                            type: number
                          mariesOuPacses:
                            type: number
                          celibataire:
                            type: number
                          divorce:
                            type: number
                    partsParPACAuDela:
                      type: number
                    partsParPACChargePartagee:
                      type: object
                      properties:
                        zeroChargePrincipale:
                          type: object
                          properties:
                            deuxPremiers:
                              type: number
                            suivants:
                              type: number
                        unChargePrincipale:
                          type: object
                          properties:
                            premier:
                              type: number
                            suivants:
                              type: number
                        deuxOuPlusChargePrincipale:
                          type: object
                          properties:
                            suivants:
                              type: number
                    bonusParentIsole:
                      type: object
                      properties:
                        auMoinsUnChargePrincipale:
                          type: number
                        zeroChargePrincipaleUnPartage:
                          type: number
                        zeroChargeprincipaleDeuxOuPlusPartage:
                          type: number
        description_cas_types:
          type: array
          items:
            type: object
            properties:
              nombre_declarants:
                type: integer
              nombre_personnes_a_charge:
                type: integer
              nombre_declarants_retraites:
                type: integer
              revenu:
                type: integer
              guadeloupe:
                type: boolean
    description_cas_types:
      type: array
      items:
        type: object
        properties:
          nombre_declarants:
            type: integer
          nombre_personnes_a_charge:
            type: integer
          nombre_declarants_retraites:
            type: integer
          revenu:
            type: integer
          outre_mer:
            type: integer
    login:
      type: object
      properties:
        email:
          type: string
    dotations:
      type: object
      properties:
        dotations:
          type: object
